"""
Module: config
"""


BOARD_BOXES = [
    {
        'position': 0,
        'type': 'PaymentBox',
        'name': 'Start',
        'payment': 1000,
    },
    {
        'position': 1,
        'type': 'TownBox',
        'name': 'Town 1',
        'price': 200,
    },
    {
        'position': 2,
        'type': 'TownBox',
        'name': 'Town 2',
        'price': 200,
    },
    {
        'position': 3,
        'type': 'TownBox',
        'name': 'Town 3',
        'price': 200,
    },
    {
        'position': 4,
        'type': 'TownBox',
        'name': 'Town 4',
        'price': 200,
    },
    {
        'position': 5,
        'type': 'TownBox',
        'name': 'Town 5',
        'price': 200,
    },
    {
        'position': 6,
        'type': 'TownBox',
        'name': 'Town 6',
        'price': 200,
    },
    {
        'position': 7,
        'type': 'TownBox',
        'name': 'Town 7',
        'price': 200,
    },
    {
        'position': 8,
        'type': 'TownBox',
        'name': 'Town 8',
        'price': 200,
    },
    {
        'position': 9,
        'type': 'TownBox',
        'name': 'Town 9',
        'price': 200,
    },
    {
        'position': 10,
        'type': 'Box',
        'name': 'Rest 1',
    },
    {
        'position': 11,
        'type': 'TownBox',
        'name': 'Town 11',
        'price': 200,
    },
    {
        'position': 12,
        'type': 'TownBox',
        'name': 'Town 12',
        'price': 200,
    },
    {
        'position': 13,
        'type': 'TownBox',
        'name': 'Town 13',
        'price': 200,
    },
    {
        'position': 14,
        'type': 'TownBox',
        'name': 'Town 14',
        'price': 200,
    },
    {
        'position': 15,
        'type': 'TownBox',
        'name': 'Town 15',
        'price': 200,
    },
    {
        'position': 16,
        'type': 'TownBox',
        'name': 'Town 16',
        'price': 200,
    },
    {
        'position': 17,
        'type': 'TownBox',
        'name': 'Town 17',
        'price': 200,
    },
    {
        'position': 18,
        'type': 'TownBox',
        'name': 'Town 18',
        'price': 200,
    },
    {
        'position': 19,
        'type': 'TownBox',
        'name': 'Town 19',
        'price': 200,
    },
    {
        'position': 20,
        'type': 'Box',
        'name': 'Rest 2',
    },
    {
        'position': 21,
        'type': 'TownBox',
        'name': 'Town 21',
        'price': 200,
    },
    {
        'position': 22,
        'type': 'TownBox',
        'name': 'Town 22',
        'price': 200,
    },
    {
        'position': 23,
        'type': 'TownBox',
        'name': 'Town 23',
        'price': 200,
    },
    {
        'position': 24,
        'type': 'TownBox',
        'name': 'Town 24',
        'price': 200,
    },
    {
        'position': 25,
        'type': 'TownBox',
        'name': 'Town 25',
        'price': 200,
    },
    {
        'position': 26,
        'type': 'TownBox',
        'name': 'Town 26',
        'price': 200,
    },
    {
        'position': 27,
        'type': 'TownBox',
        'name': 'Town 27',
        'price': 200,
    },
    {
        'position': 28,
        'type': 'TownBox',
        'name': 'Town 28',
        'price': 200,
    },
    {
        'position': 29,
        'type': 'TownBox',
        'name': 'Town 29',
        'price': 200,
    },
    {
        'position': 30,
        'type': 'Box',
        'name': 'Rest 3',
    },
    {
        'position': 31,
        'type': 'TownBox',
        'name': 'Town 31',
        'price': 200,
    },
    {
        'position': 32,
        'type': 'TownBox',
        'name': 'Town 32',
        'price': 200,
    },
    {
        'position': 33,
        'type': 'TownBox',
        'name': 'Town 33',
        'price': 200,
    },
    {
        'position': 34,
        'type': 'TownBox',
        'name': 'Town 34',
        'price': 200,
    },
    {
        'position': 35,
        'type': 'TownBox',
        'name': 'Town 35',
        'price': 200,
    },
    {
        'position': 36,
        'type': 'TownBox',
        'name': 'Town 36',
        'price': 200,
    },
    {
        'position': 37,
        'type': 'TownBox',
        'name': 'Town 37',
        'price': 200,
    },
    {
        'position': 38,
        'type': 'TownBox',
        'name': 'Town 38',
        'price': 200,
    },
    {
        'position': 39,
        'type': 'TownBox',
        'name': 'Town 39',
        'price': 200,
    },
]
